server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banddb}
    username: ${SPRING_DATASOURCE_USERNAME:band}
    password: ${SPRING_DATASOURCE_PASSWORD:bandpass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
app:
  jwt:
    secret: ${APP_JWT_SECRET:dev-secret-change-me}
    issuer: band-app
    expirationMinutes: 60
